### ISSUE TITLE
ModuleNotFoundError: No module named 'pts'

### ISSUE THREAD

**Issue by Joston3** [ServiceNow/tactis#35] opened 2024-08-29 16:46 UTC
<img width="198" alt="pts" src="https://github.com/user-attachments/assets/31ca03ae-fa86-4c04-afe5-234dbfdb5c99">

**Comment by aldro61** [comment] 2024-08-29 17:18
Hi @Joston3 seems like a duplicate of #34. Please reopen if needed.

**Closed as completed by aldro61** 2024-08-29 17:18 UTC

**Comment by Joston3** [comment] 2024-08-30 03:42
![1724989238199](https://github.com/user-attachments/assets/06a66ff5-6247-4e9f-b71b-6f3b8733e6ff)
<img width="482" alt="1724989235949" src="https://github.com/user-attachments/assets/1edbff8a-5843-44fc-b4cd-4d6087a0408e">
why this problem still occurs?😭

**Comment by Joston3** [comment] 2024-08-30 03:44
why this problem still occurs?😭
<img width="392" alt="1724989420658" src="https://github.com/user-attachments/assets/acba6c87-afab-4633-95c9-0ddbaf65c654">
<img width="455" alt="1724989445782" src="https://github.com/user-attachments/assets/e55cbea0-76f7-4fca-9605-e671dc6d3a63">
